### ISSUE TITLE
Minor Issue in GPIO Documentation

### ISSUE THREAD

**Issue by ofthedove** [OnionIoT/Onion-Docs#1]
In Onion Omega2 Docs/Using the Omega/Using the Omega's GPIOs/Multiplexed GPIOs under "Changing the GPIO Function" the second paragraph says, 

> To illustrate the above, the following command will set I2C pins to GPIO mode:

but the example shows changing the uart1 pins to gpio

`omega2-ctrl gpiomux set uart1 gpio`

The second paragraph should be updated to read

> To illustrate the above, the following command will set UART1 pins to GPIO mode:

or the example should be updated

**Comment by greenbreakfast** [comment]
should be fixed now, thanks for the tip!
