### ISSUE TITLE
Php : add filter extension.

### ISSUE THREAD

**Issue by jorismulliez** [OnionIoT/Onion-Docs#12]
Hi,

I would like to see the php extension "filter" on the omega.
We already discuss things here : https://community.onion.io/topic/1241/omega2-php-mods-add-filter
And I open an issue here : https://github.com/openwrt/packages/issues/3831

It seems that you "just have to"  
> add CONFIG_PHP7_FILTER=y to the build configuration

I don't know if it's possible ? I don't know if the new php package wqill become very heavier...

Thanks a lot,

**Comment by greenbreakfast** [comment]
PHP filter configuration is now enabled! You will likely have to uninstall the old PHP packages, run opkg update, and then install the new packages.
