### ISSUE TITLE
Make zeroconf/bonjour work on android ?

### ISSUE THREAD

**Issue by jorismulliez** [OnionIoT/Onion-Docs#13]
Hi,

I don't know if there is a solution, but, I don't get any response for now.
So, is it possible make the zeroconf/bonjour service work on android devices ? I don't find any end user option/app for that...

The discussion is here : https://community.onion.io/topic/1261/how-work-the-address-omega-local

Thanks a lot,

**Comment by gbo-actual** [comment]
Unfortunately there isn't anything we can do on that end, it's entirely dependent on Android.
