### ISSUE TITLE
1-wire tutorial for omega 2?

### ISSUE THREAD

**Issue by jorismulliez** [OnionIoT/Onion-Docs#18]
Can you provide a tutorial for using 1-wire on omega2/2+ ?
https://wiki.onion.io/Tutorials/Reading-1Wire-Sensor-Data

Thanks,

**Comment by pieman64** [comment]
@jorismulliez what errors did you get when you tried to use 1Wire with the 2 and 2+?

**Comment by jorismulliez** [comment]
I've not try yet. Because some other users got errors :
https://community.onion.io/topic/1310/1-wire-temperature-sensor-ds18b20-on-omega2/7

**Comment by jorismulliez** [comment]
Hi,

Any news for this problem ?

Thanks,

**Comment by greenbreakfast** [comment]
Planning to work look into it this week. Have you tried it out on your end?

**Comment by jorismulliez** [comment]
Hi,

I didn't try yet because I'm scared of burn my omega with a mis-configured pin!
And because I read on the thread pointed before that 1-wire isn't functional.

Thanks for your help!

**Comment by pieman64** [comment]
@greenbreakfast looking forward to the fix Lazar.

**Comment by pieman64** [comment]
@greenbreakfast thanks for the b151 firmware upgrade.

@jorismulliez confirmed as working on my 2+

![ds18b20_omega2plus](https://cloud.githubusercontent.com/assets/8315296/22594203/bcb7fac0-ea2a-11e6-8776-1eaf2777fd6f.JPG)

**Comment by greenbreakfast** [comment]
@pieman64 no problem! I'll update the known issues page.
Some other issues popped up in the firmware so I haven't advertised it yet :)

**Comment by greenbreakfast** [comment]
Whoops, guess we still need a tutorial, gonna reopen this issue

**Comment by greenbreakfast** [comment]
Added an article! Find it published here: https://docs.onion.io/omega2-docs/communicating-with-1w-devices.html

**Comment by jorismulliez** [comment]
@greenbreakfast Thanks for the work,
But it seems not to work for me, see : https://community.onion.io/topic/1310/1-wire-temperature-sensor-ds18b20-on-omega2/32
