### ISSUE TITLE
Typo in Fast-GPIO Documentation

### ISSUE THREAD

**Issue by ofthedove** [OnionIoT/Onion-Docs#2]
In Onion Omega2 Docs/Using the Omega/Using the Omega's GPIOs/Fast-GPIOs under "Command Usage:" the first paragraph reads,

>For a print-out of the usage, run `fast-gpio` with on the command line:

"with on" is redundant, should use one or the other, probably "on"

New line should read:

>For a print-out of the usage, run `fast-gpio` on the command line:

**Comment by greenbreakfast** [comment]
should be fixed now, thanks for the tip!
