### ISSUE TITLE
Typo / Strange placeholder in the Linux introduction section

### ISSUE THREAD

**Issue by uberdriven** [OnionIoT/Onion-Docs#23]
Hey guys, just wanted to report a small typo in the section:
`Linux Introduction` > `Exploring The File System` > `How To Navigate In Linux`.
 
Under `ls command`, the following sentence can be found ;)
*So let’s see what’s in our homeGETPROPERNAMEFORTHIS directory.*

Keep up the great work!
Jaime

**Comment by greenbreakfast** [comment]
Fixed! Need to go over these Linux intro articles a few more times!

Thanks for the heads up and enjoy your Omega!
