### ISSUE TITLE
Incorrect command for copying overlay to external storage in Omega2/Documentation/Doing-Stuff/Boot-from-External-Storage.md

### ISSUE THREAD

**Issue by dlparker** [OnionIoT/Onion-Docs#29]
Says:

> mount /dev/<device name> /mnt ; tar -C /overlay -cvf - . | tar -C /mnt -xf - ; umount /mnt

Should say

mount /dev/<device name> /mnt/<device  name> ; tar -C /overlay -cvf - . | tar -C /mnt/<device name> -xf - ; umount /mnt/<device name>

It should do that because the instructions just before have you creating the mount point using that naming scheme. If you follow the instructions exactly, then the "/mnt" path is a regular directory, and the mount fails and the tar copies the files to that directory.

After moving the copied files to the /mnt/<device name> directory, I continued with the instructions and it worked as described.

**Comment by thepiper** [comment]
Damn, good catch. Expect a fix soon (tm).
