### ISSUE TITLE
Expired SSL Certificate on *.onion.io

### ISSUE THREAD

**Issue by lfuelling** [OnionIoT/Onion-Docs#31]
Hi,

as I previously wrote you on Twitter, your SSL Certificate has expired yesterday. 

You should renew it, because the cloud, the docs (hsts) and the Omega2 Setup don't seem to work properly and it's not very trust generating in general.

Sorry if this is the wrong place for it, I don't know where else to post this.

**Comment by greenbreakfast** [comment]
fixed! thanks for reporting it!
