### ISSUE TITLE
syntax error: unexpected "(" (expecting ")")

### ISSUE THREAD

**Issue by felipecespedes** [OnionIoT/Onion-Docs#42]
Hi, I'm trying to get data of a DHT22 sensor in Omega2, but am getting the following error:

```bash
line 1: syntax error: unexpected "(" (expecting ")")
```

Any ideas about it? Thanks.

**Comment by greenbreakfast** [comment]
hi, which guide are you using?

**Comment by viwell** [comment]
This one https://github.com/OnionIoT/Onion-Docs/blob/master/Omega2/Projects/PHP-DHT11-DHT22-Sensor-Examples.md

**Comment by viwell** [comment]
Hi, seems that checkHumidity binaries you guys provided are for the Omega1, where can I find binaries for the Omega2?

**Comment by DanOBrien** [comment]
I'm getting the same message:

root@onion1:~/checkHumidity/bin# ./checkHumidity 1 DHT11
./checkHumidity: line 1: syntax error: unexpected "(" (expecting ")")


I'm using this hardware:
Codename:	Ando
Model:	Onion Omega2+
Revision:	R1
Firmware:	0.1.10 (b160)

The page: https://wiki.onion.io/Tutorials/PHP-DHT11-DHT22-Sensor-Examples  and  https://github.com/OnionIoT/Onion-Docs/blob/master/Omega2/Projects/PHP-DHT11-DHT22-Sensor-Examples.md seem to be the same thing, but not valid for Omega2.

**Comment by mdoary** [comment]
Anyone get this working?

**Comment by h0l0gram** [comment]
@DanOBrien @viwell 
For the Omega2(+) adapted sources see https://github.com/h0l0gram/omega2-checkHumidity.
There is even a compiled binary for **firmware 0.1.10 b160** available.

**Comment by greenbreakfast** [comment]
We've rolled the DHT sensor code into our package repo, for more details see: https://onion.io/2bt-reading-dht-sensor-data/
