### ISSUE TITLE
Documentation Issue - incorrect Pin

### ISSUE THREAD

**Issue by willemvisser** [OnionIoT/Onion-Docs#48]
Hi there,

I suspect you have made a mistake in your servo documentation at:  https://docs.onion.io/omega2-maker-kit/maker-kit-servo-h-bridge.html#

You instruct the following:  3) Take one M-M jumper and connect 1,2EN on the IC (row 5 on our board) to the Vcc rail.

That however will then not allow you to adjust the speed at which the motor turns, and the sample code provided will always turn the motor at full speed, despite setting it to something else.  I suspect that the text should read:

3) Take one M-M jumper and connect 1,2EN on the IC (row 5 on our board) to channel S2 on the PWM board.

Willem

**Comment by pavelmetrokhin** [comment]
Hi Willemvisser,
Thanks for noticing that. The found mistake was related to the previous picture of the setting which connection was `1,2EN to S2 signal`. Now, the picture represents the description.
