### ISSUE TITLE
diagram wrong resistor

### ISSUE THREAD

**Issue by aklein-dex** [OnionIoT/Onion-Docs#54]
On this picture: https://github.com/OnionIoT/Onion-Docs/blob/master/Omega2/Kit-Guides/Arduino/diagrams/04-circuit-diagram.png

The 200Ω resistor next to the GPIO2 should be 5.1kΩ to match the components listed in "What You'll Need".

**Comment by greenbreakfast** [comment]
fixed! thanks for letting us know!
