### ISSUE TITLE
Invalid instructions for cross compiling

### ISSUE THREAD

**Issue by andreas-lundgren-storytel** [OnionIoT/Onion-Docs#58]
The github repo `https://git.lede-project.org/source.git` referenced to from https://docs.onion.io/omega2-docs/cross-compiling.html is not available.

**Comment by andreas-lundgren-storytel** [comment]
It's also incorrect here, https://lede-project.org/docs/guide-developer/install-buildsystem

**Comment by greenbreakfast** [comment]
Fixed now. Thanks for the heads up!
