### ISSUE TITLE
Connectivity: Can't find Omega AP after connecting to PEAP network

### ISSUE THREAD

**Issue by stingray127** [OnionIoT/Onion-Docs#65]
I followed the instructions from Connect-to-enterprise-wifi.md but after I run /etc/init.d/network restart, the Omega's AP disappears from my Mac's listed wifi networks and I can no longer connect to the board. This effectively renders my Omega useless since I have to be able to connect to the wifi network to ssh into the board and do anything on it. 

Are the instructions I followed up to date? I have an Omega 2 and a Power Dock 2.

**Comment by greenbreakfast** [comment]
Hi, all of the content from https://github.com/OnionIoT/wiki only refers to the original Omega, that was launched in 2015.
For Omega2 documentation, go to docs.onion.io.
To answer your question, PEAP networks are not supported with the Omega2.

**Comment by stingray127** [comment]
Thank you!
