### ISSUE TITLE
Typo in "Using the GPS Expansion" Documentation

### ISSUE THREAD

**Issue by AlienSkills** [OnionIoT/Onion-Docs#9]
There is a typo in the Onion Omega2 Docs under Onion-Docs/Omega2/Documentation/Doing-Stuff/Expansions/Using-the-GPS-Expansion. Under the heading "Reading NMEA Data Using ogps" you have instructions stating:

> You can also use ogps to access relevant data offered up by the GPS via ubus calls. To install ogps enter the following commands.
> 
> ```
> opkg update
> opkg install opgs
> ```

opgs is misspelled as "opgs" in the command "opkg install ogps" and I don't beleave that is what you're trying to install there as opgs is not a real package. 

New instructions should look like this:

> You can also use ogps to access relevant data offered up by the GPS via ubus calls. To install ogps enter the following commands.
> 
> ```
> opkg update
> opkg install ogps
> ```

**Comment by greenbreakfast** [comment]
good eye! should be fixed now!
