### ISSUE TITLE
Typo/missing word in "Using the Command Line"

### ISSUE THREAD

**Issue by pdragy** [OnionIoT/Onion-Docs#92]
[line in connecting.md](https://github.com/OnionIoT/Onion-Docs/blob/dfe974f2ddcd10f86ecd25b2c7322933ebcbaf28/Omega2/Documentation/Get-Started/Using-the-Command-Line/connecting.md?plain=1#L129)

... will make your Omega even more since passwords can... 
->
... will make your Omega even more **secure** since passwords can ...

**Comment by greenbreakfast** [comment]
Thanks for pointing this out! Fixed!
